### ISSUE TITLE
armeabi-v7a

### ISSUE THREAD

**Issue by bettse** [reverseengineeringer/com.nianticlabs.pokemongo#1]
When decompiled, it seems to drop the lib/armeabi-v7a/*.so files.  You can see the files in question at another repo: https://github.com/Superviral/PokemonGO-Decompiled/tree/master/lib/armeabi-v7a

**Comment by reverseengineeringer** [comment]
They are here: https://github.com/reverseengineeringer/com.nianticlabs.pokemongo/tree/master/apktool/lib/armeabi-v7a
